---
title: Mood indicator
hero_image: images/banner.png
description: Create a mood indicator with coloured lights to emote your current mood
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Design your mood check-in
  - 
    title: Code your mood lights
    completion:
      - engaged
  - 
    title: Change your mood
  - 
    title: Craft your device
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
